### ISSUE TITLE
MISP API output bot duplicating events in MISP

### ISSUE THREAD

**Issue by panpietrek** [certat/intelmq-docker#6] opened 2021-06-04 13:11 UTC
Hi,

I'm trying to get intelmq (docker version) to parse viriback (https://tracker.viriback.com/) data into a MISP instance using the guide at: https://intelmq.readthedocs.io/en/latest/user/feeds.html#viriback
The issues I'm having is that the bot that supposed to insert the events into my MISP instance (intelmq.bots.outputs.misp.output_api) does not seem to be checking for exising events in MISP and just feeds it with new events every time I restart the botnet and thus flooding the MISP instance with duplicated events.
I'm running MISP 2.4.143 with intelmq-docker 2.3.3 container (pulled with: git clone --recursive https://github.com/certat/intelmq-docker.git at 04.06.2021)

I did recently update my MISP instance from .133 to .143 hoping this'd resolve the problem, but it's still the same.

Are there any details I'm missing here? Any logs I could look into?
Thanks.

**Comment by waldbauer-certat** [comment] 2021-06-07 07:48
Hey @panpietrek,

awesome that you're using the docker image :)

> I'm running MISP 2.4.143 with intelmq-docker 2.3.3 container (pulled with: git clone --recursive https://github.com/certat/intelmq-docker.git at 04.06.2021)

Are you using the docker-compose for intelmq or you've used the docker-cli commands?

> Any logs I could look into?

Logs are located at `- ./intelmq_logs`

**Comment by schacht-certat** [comment] 2021-06-07 08:37
> The issues I'm having is that the bot that supposed to insert the events into my MISP instance (intelmq.bots.outputs.misp.output_api) does not seem to be checking for exising events in MISP and just feeds it with new events every time I restart the botnet and thus flooding the MISP instance with duplicated events.

Maybe you want to have a look at the deduplicator bot: https://intelmq.readthedocs.io/en/maintenance/user/bots.html#deduplicator

**Comment by panpietrek** [comment] 2021-06-07 08:40
> 
> 
> Hey @panpietrek,
> 
> awesome that you're using the docker image :)
> 
> > I'm running MISP 2.4.143 with intelmq-docker 2.3.3 container (pulled with: git clone --recursive https://github.com/certat/intelmq-docker.git at 04.06.2021)
> 
> Are you using the docker-compose for intelmq or you've used the docker-cli commands?
> 
> > Any logs I could look into?
> 
> Logs are located at `- ./intelmq_logs`


Hi,

Thanks for your reply.
I'm using docker-compose and the docker-compose.yml file that comes with the repo.
As for the logs, I already checked MISP-API-Output.log file and it seems like the MISP-API-Output bot does not pickup that there already are some exising events in MISP. As far as I can tell, it should say something along the lines of: "MISP-API-Output - INFO - Found MISP events matching "blah, blah" -> not inserting."
It does not, and instead simply goes on with "MISP-API-Output - INFO - Inserted new MISP event with id: 11388" and creates a duplicate event.

Here's my runtime.conf:

`{
    "URL-Fetcher-Collector": {
        "parameters": {
            "extract_files": false,
            "gpg_keyring": null,
            "http_password": null,
            "http_url": "https://tracker.viriback.com",
            "http_url_formatting": false,
            "http_username": null,
            "name": "Unsafe sites",
            "provider": "ViriBack",
            "rate_limit": 3600,
            "signature_url": null,
            "signature_url_formatting": false,
            "ssl_client_certificate": null,
            "verify_pgp_signatures": false,
            "http_verify_cert": false
        },
        "name": "URL Fetcher",
        "group": "Collector",
        "module": "intelmq.bots.collectors.http.collector_http",
        "description": "Fetch reports from an URL.",
        "enabled": true,
        "run_mode": "continuous",
        "groupname": "collectors",
        "bot_id": "URL-Fetcher-Collector"
    },
    "HTML-Table-Parser": {
        "parameters": {
            "attribute_name": "",
            "attribute_value": "",
            "columns": [
                "malware.name",
                "source.url",
                "source.ip",
                "time.source"
            ],
            "default_url_protocol": "http://",
            "ignore_values": [
                "",
                "",
                "",
                ""
            ],
            "skip_table_head": true,
            "split_column": "",
            "split_index": 0,
            "split_separator": "",
            "table_index": 0,
            "time_format": "from_format_midnight|%d-%m-%Y",
            "type": "malware-distribution"
        },
        "name": "HTML Table",
        "group": "Parser",
        "module": "intelmq.bots.parsers.html_table.parser",
        "description": "Parse HTML table data.",
        "enabled": true,
        "run_mode": "continuous",
        "groupname": "parsers",
        "bot_id": "HTML-Table-Parser"
    },
    "MISP-API-Output": {
        "parameters": {
            "add_feed_name_as_tag": true,
            "add_feed_provider_as_tag": true,
            "misp_additional_correlation_fields": [],
            "misp_additional_tags": [],
            "misp_key": "alTNJAwGugWeCyldRXGLPaousLIEfsKWQigD5yh6",
            "misp_publish": false,
            "misp_tag_for_bot": "test_tag",
            "misp_to_ids_fields": [],
            "misp_url": "https://mymispserver.fqdn/",
            "significant_fields": [
                "malware.name",
                "source.url",
                "source.ip"
            ]
        },
        "name": "MISP API",
        "group": "Output",
        "module": "intelmq.bots.outputs.misp.output_api",
        "description": "Insert events into a MISP instance.",
        "enabled": true,
        "run_mode": "continuous"`

**Comment by panpietrek** [comment] 2021-06-07 09:02
> 
> 
> > The issues I'm having is that the bot that supposed to insert the events into my MISP instance (intelmq.bots.outputs.misp.output_api) does not seem to be checking for exising events in MISP and just feeds it with new events every time I restart the botnet and thus flooding the MISP instance with duplicated events.
> 
> Maybe you want to have a look at the deduplicator bot: https://intelmq.readthedocs.io/en/maintenance/user/bots.html#deduplicator

I did see it when I was trying to solve this problem, but it seems to me it'd make the entire setup a bit overcomplicated, as the bot would somehow have to read existing events from MISP, then compare the new ones and deduplicate the output before pusing it via MISP API. Also, the deduplication functionality is already there for the MISP API bot, so I'd rather fix that properly and avoid such workarounds.
Thanks anyway ;)

**Comment by wagner-certat** [comment] 2021-06-07 15:39
I removed the misp API key from your post here, but it still is on pastebin, please change it!

Maybe @pettai or @bernhardreiter can help with this issue?

**Comment by bernhardreiter** [comment] 2021-06-08 06:31
If there is not log entry for a matching event, it means that the search at https://github.com/certtools/intelmq/blob/8757ed715cb6f4221762f422147620566abf6ad2/intelmq/bots/outputs/misp/output_api.py#L124 fails. Maybe the pymisp version changed or MISP does something after the initial insertion. If you know some python, you could enter more logging entries there and try to do the search manually on a python prompt, to see what is going wrong.

**Comment by bernhardreiter** [comment] 2021-06-08 12:29
> Could you please tell me what permissions (MISP side) are required for an account to be able to write events to MISP?

I don't know. Would be a MISP or pyMISP question.

**Comment by wagner-certat** [comment] 2021-06-08 12:33
> > Could you please tell me what permissions (MISP side) are required for an account to be able to write events to MISP?
> 
> I don't know. Would be a MISP or pyMISP question.

@Rafiot can you help here?

**Comment by wagner-certat** [comment] 2021-06-21 10:36
Closing here as this is not a bug in the Docker container build scripts.

@panpietrek You could reach out the MISP support for guidance on this, or ask on the intelmq-users mailing list: https://lists.cert.at/cgi-bin/mailman/listinfo/intelmq-users
Unfortunately the people active here do not have enough insight about MISP to help you directly

**Closed by wagner-certat** 2021-06-21 10:36 UTC
