### ISSUE TITLE
Getting a 404 error when trying to access intelmq-manager

### ISSUE THREAD

**Issue by jaylinski** [certat/intelmq-docker#5] opened 2021-04-14 21:52 UTC
Hi!

I just tried this docker-setup as described in https://github.com/certat/intelmq-docker#fastest-way-to-run--deploy, but when I try to open http://127.0.0.1:1337/ I'm getting a 404 nginx error.

This is because `docker-compose.yml` maps the folder `./intelmq-manager/html` (https://github.com/certat/intelmq-docker/blob/main/docker-compose.yml#L19), which is empty when I check out this repository... am I missing something?

**Comment by waldbauer-certat** [comment] 2021-04-15 10:13
Hey @jaylinski,

thanks for your report. This should be fixed in the latest update, please pull the latest docker images from dockerhub :)

**Comment by jaylinski** [comment] 2021-04-15 18:11
Works, thanks for the quick fix!

**Comment by einar-lanfranco** [comment] 2021-09-16 16:00
Hi folks, it happened again, if i use build.sh to build local images it works great but if i use images from dockerhub intelmq-nginx www forder is empty.

**Comment by waldbauer-certat** [comment] 2021-09-20 09:48
> Hi folks, it happened again, if i use build.sh to build local images it works great but if i use images from dockerhub intelmq-nginx www forder is empty.

Hello @einar-lanfranco :wave: 

I checked the /www folder from certat/intelmq-docker & cant reproduce your problem.
```
/www # ls -al
total 108
drwxr-xr-x    1 root     root          4096 Sep 14 16:42 .
drwxr-xr-x    1 root     root          4096 Sep 20 09:44 ..
-rw-r--r--    1 root     root         11789 Sep 14 16:42 about.html
-rw-r--r--    1 root     root          9066 Sep 14 16:42 check.html
-rw-r--r--    1 root     root         14102 Sep 14 16:42 configs.html
drwxr-xr-x    2 root     root          4096 Mar 12  2021 css
drwxr-xr-x    2 root     root          4096 Mar 12  2021 images
-rw-r--r--    1 root     root         12107 Sep 14 16:42 index.html
drwxr-xr-x    2 root     root          4096 Sep 14 16:42 js
drwxr-xr-x    2 root     root          4096 Mar 12  2021 less
-rw-r--r--    1 root     root         11992 Sep 14 16:42 management.html
-rw-r--r--    1 root     root         15991 Sep 14 16:42 monitor.html
drwxr-xr-x    8 root     root          4096 Mar 12  2021 plugins
```

You can check the image yourself if you run `docker run -it certat/intelmq-nginx:latest sh` & inside the container with `ls -al`.

Have you used the docker-compose or the manual docker setup?
Have you checked if the docker containers are up & running with `docker ps`?
Are you using the latest version?

**Comment by einar-lanfranco** [comment] 2021-09-20 11:32
Last friday I did what you say at least twice and it didnt work, i dont know what happened, now i deleted all and started again and  its working, it doesnt make sense, i dont know, probably my fault, sorry for wasting your time! :( And thanks again

**Comment by wagner-certat** [comment] 2021-09-21 08:04
Thanks for the feedback. If you find any issue or possible improvement to prevent such errors, please let us know.

**Closed** 2021-09-21 08:04 UTC
Labels: bug
